### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by escapezn** [HFrost0/danmakuC#2]
Windows 10，python 3.10，danmukuC 0.22

无法处理任何弹幕文件，提示错误
```
danmakuC .\[SweetSub]_Do_It_Yourself___-_02_[WebRip][1080P][AVC_8bit][CHS].xml -o 1.ass
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Users\volks\Downloads\mpv\Scripts\danmakuC.exe\__main__.py", line 7, in <module>
  File "C:\Users\volks\Downloads\mpv\lib\site-packages\danmakuC\__main__.py", line 61, in main
    output = proto2ass(
  File "C:\Users\volks\Downloads\mpv\lib\site-packages\danmakuC\bilibili.py", line 25, in proto2ass
    target.ParseFromString(proto_bytes)
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by HFrost0** [comment]
目前版本danmakuC仅支持protobuf格式的b站弹幕，但0.2.2仍提供了底层由C++实现的通用api来将其他格式或其他网站的弹幕转换为ass，详情可见`danmakuC._c.ass`或`danmakuC.bilibili`中的代码。

如果你有兴趣，也可以提交一个PR，让danmakuC变得更好
